---
title: "Expressing Design Formula Exercises"
author: "Stephen Blatti"
date: "August 21, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Suppose we have an experiment with the following design: on three different days, we perform an experiment with two treated and two control samples. We then measure some outcome Y_i, and we want to test the effect of condition, while controlling for whatever differences might have occured due to the the different day (maybe the temperature in the lab affects the measuring device). Assume that the true condition effect is the same for each day (no interaction between condition and day). We then define factors in R for 'day' and for 'condition'.

              day:  A   B   C
      condition: --------------
      treated    |  2   2   2
      control    |  2   2   2

1. Given the factors we have defined above, and not defining any new ones, which of the following R formula will produce a design matrix (model matrix) that let's us analyze the effect of condition, controlling for the different days:
~ day + condition correct
~ condition
~ day
~ A + B + C + control + treated
~ B + C + treated
